"""Rename type to maintenance_type

Revision ID: d8d9c1f15c79
Revises: 
Create Date: 2025-06-28 14:00:55.219900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d9c1f15c79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('maintenance_type')

    # ### end Alembic commands ###
